global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'binance-worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['binance-worker:3001']

  - job_name: 'telegram-bot'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['telegram-bot:3000']
